export const SET_SHORT_SURAH_LOADING = "SET_SHORT_SURAH_LOADING";
export const SHORT_SURAH_GET_SUCCESS = "SHORT_SURAH_GET_SUCCESS";

export const SET_FULL_SURAH_LOADING = "SET_FULL_SURAH_LOADING";
export const FULL_SURAH_GET_SUCCESS = "SET_FULL_SURAH_GET_SUCCESS";

export const SET_DARK_MODE = "SET_DARK_MODE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_ARABIC_TEXT_SIZE = "SET_ARABIC_TEXT_SIZE";
export const SET_BANLGA_TEXT_SIZE = "SET_BANLGA_TEXT_SIZE";
export const SET_ENGLIS_TEXT_SIZE = "SET_ENGLIS_TEXT_SIZE";
export const SET_TAJWEED = "SET_TAJWEED";
export const SET_HAFEZI_FONT = "SET_HAFEZI_FONT";
export const SAVE_TO_READ_LATER = "SAVE_TO_READ_LATER";
export const SET_LAST_READ_AYAH = "SET_LAST_READ_AYAH";
export const SET_LAST_READ_SURAH = "SET_LAST_READ_SURAH";
export const SET_AYAH_DETAILS = "SET_AYAH_DETAILS";
export const SET_IS_SHOW_BANGLA_TEXT = "SET_IS_SHOW_BANGLA_TEXT";
export const SET_IS_SHOW_ENGLISH_TEXT = "SET_IS_SHOW_ENGLISH_TEXT";
export const SET_IS_SHOW_TAFSIR = "SET_IS_SHOW_TAFSIR";
export const SET_IS_SHOW_COPY_BUTTON = "SET_IS_SHOW_BUTTON";
export const SET_IS_SHOW_SAVE_BUTTON = "SET_IS_SHOW_SAVE_BUTTON";
export const SET_FAVOURITE_SURAH_LIST = "SET_FAVOURITE_SURAH_LIST";
export const SET_FULL_SHORT_SURAH_LIST = "SET_FULL_SHORT_SURAH_LIST";
export const SET_IS_SHOW_AUDIO_PLAYER = "SET_IS_SHOW_AUDIO_PLAYER";
